# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('weight', models.PositiveIntegerField(default=100, help_text='Чем больше, тем приоритетнее', verbose_name='Вес')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('category', models.CharField(choices=[('sale', 'Продажа'), ('buy', 'Покупка')], max_length=4, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name_plural': 'Обьявления',
                'verbose_name': 'Обьявление',
                'ordering': ['-weight', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('weight', models.PositiveIntegerField(default=100, help_text='Чем больше, тем приоритетнее', verbose_name='Вес')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
            ],
            options={
                'verbose_name_plural': 'Теги',
                'verbose_name': 'Тег',
            },
        ),
        migrations.AddField(
            model_name='boardpost',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='boards.BoardTag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
